sale_tab_xpath = "//span[text()='Sale']/parent::a"
search_field_xpath = "//input[@id ='search']"
search_result_xpath = "//span[@data-ui-id ='page-title-wrapper']"
commodity_path = "//a[contains(@href, 'tees-men.') and text()='Tees']"
commodity_text_to_compare_path = "//span [contains(@class, 'base') and text()='Tees']"
home_button_xpath = "//a[@title='Go to Home Page']"
home_page_title_path = "//title[text()='Home Page']"
